# what is package

- package is a collection of modules and modules is a collection of functions
- they are some packages

#1)numpy:

- it is high performance multi dimentional array
- it can deal with n dimentional arrays
- it is used for scientific calculation purpose
- it can store and manipulate the huge amount of data
- it performs mathematical and logical operation of arrays
- it is faster than repular python list

In [ ]:
# install numpy

!pip install numpy


In [ ]:
#importing numpy

import numpy as np  #np is like pet name for numpy
#creating numpy

#creating 1-D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#creating 2-D array
b = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(b)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#creating 3-D array
c = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(c)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [ ]:
#creating 4-D array
d = np.array([[[[1,2,3],[1,2,3],[1,2,3]]]])
print(d)

[[[[1 2 3]
   [1 2 3]
   [1 2 3]]]]


In [ ]:
#creating 5-D array
e = np.array([[[[[1,2,3],[1,2,3],[1,2,3]]]]])
print(e)

[[[[[1 2 3]
    [1 2 3]
    [1 2 3]]]]]


#initial placeholders

1)zeros:

- to create all values with zeros

In [ ]:
#create array with zeros

import numpy as np
np.zeros([2,3,3])  #syntax->(shape,row,coloumn) and it can takes first priority from end side
#3-D array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
import numpy as np
np.zeros([3])  #1-D array

array([0., 0., 0.])

In [ ]:
import numpy as np
np.zeros([3,3])  #2-D array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
np.zeros([3,1,3,3])  #4-D array

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
import numpy as np
np.zeros([1,1,3,3,3]) #5-D array

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

2)ones:

- to create all the values in ones

In [ ]:
import numpy as np
np.ones([3])    #1-D array

array([1., 1., 1.])

In [ ]:
import numpy as np
np.ones([3,3])   #2-D array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import numpy as np
np.ones([1,3,3])  #3-D array

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
import numpy as np
np.ones([1,2,3,3])  #4-D array

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [ ]:
import numpy as np
np.ones([1,1,2,3,3])     #5-D array

array([[[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]]])

3)evenly spaced values:

- it is simply known as skip the values
- syntax-> np.arange(start,end,step)
- step = n-1(number-1)

In [ ]:
# creating an array of evenly spaced values

import numpy as np
a = np.arange(1,15,2)     #syntax-> np.arange(start value,end value,step value)(n-1)
#[(n-1) = 2-1 = 1 and skips the one value and print next number]
print(a)

[ 1  3  5  7  9 11 13]


In [ ]:
import numpy as np
b = np.arange(1,10,3)
#[(n-1) = 3-1 = 2 and skips the 2 values and print next number]
print(b)

[1 4 7]


In [ ]:
import numpy as np
c = np.arange(1,100,15)
#[(n-1) = 15-1 = 14 and skips the 14 values and print next number]
print(c)

[ 1 16 31 46 61 76 91]


4)evenly spaced samples

- it is simply known as divide into parts by mentioned value
- syntax -> np.linspace(starting,ending,how many parts)

In [ ]:
import numpy as np
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
import numpy as np
b = np.linspace(1,20,20)
print(b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


In [ ]:
import numpy as np
c = np.linspace(1,10,20)
print(c)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [ ]:
import numpy as np
d = np.linspace(10,20,40)
print(d)

[10.         10.25641026 10.51282051 10.76923077 11.02564103 11.28205128
 11.53846154 11.79487179 12.05128205 12.30769231 12.56410256 12.82051282
 13.07692308 13.33333333 13.58974359 13.84615385 14.1025641  14.35897436
 14.61538462 14.87179487 15.12820513 15.38461538 15.64102564 15.8974359
 16.15384615 16.41025641 16.66666667 16.92307692 17.17948718 17.43589744
 17.69230769 17.94871795 18.20512821 18.46153846 18.71794872 18.97435897
 19.23076923 19.48717949 19.74358974 20.        ]


In [ ]:
import numpy as np
e = np.linspace(100,120,30)
print(e)

[100.         100.68965517 101.37931034 102.06896552 102.75862069
 103.44827586 104.13793103 104.82758621 105.51724138 106.20689655
 106.89655172 107.5862069  108.27586207 108.96551724 109.65517241
 110.34482759 111.03448276 111.72413793 112.4137931  113.10344828
 113.79310345 114.48275862 115.17241379 115.86206897 116.55172414
 117.24137931 117.93103448 118.62068966 119.31034483 120.        ]


5) create constant array (or) same number repeated

- np.full()

In [ ]:
#for 1-D array
import numpy as np
arr = np.full((10),45)  #for 1d array np.full((coloumns),value)
print(arr)
print(arr.ndim) #ndim define for array dimension

[45 45 45 45 45 45 45 45 45 45]
1


In [ ]:
import numpy as np
arr = np.full((12),17)
print(arr)

[17 17 17 17 17 17 17 17 17 17 17 17]


In [ ]:
import numpy as np
arr = np.full((10),(18))
print(arr)

[18 18 18 18 18 18 18 18 18 18]


In [ ]:
import numpy as np
arr = np.full((10),10)
print(arr)

[10 10 10 10 10 10 10 10 10 10]


In [ ]:
import numpy as np
arr = np.full((7),7)
print(arr)

[7 7 7 7 7 7 7]


In [ ]:
#2-D array

import numpy as np
arr = np.full((2,2),45)  #np.full((rows,coloumns),value)
print(arr)

[[45 45]
 [45 45]]


In [ ]:
import numpy as np
arr = np.full((3,3),10)
print(arr)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
import numpy as np
arr = np.full((4,4),17)
print(arr)

[[17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]]


In [ ]:
import numpy as np
arr = np.full((5,5),18)
print(arr)

[[18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]]


In [ ]:
import numpy as np
arr = np.full((6,6),7)
print(arr)

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [ ]:
#3-D array

import numpy as np
arr = np.full((1,2,2),45)
print(arr)

[[[45 45]
  [45 45]]]


In [ ]:
import numpy as np
arr =np.full((1,3,3),18)
print(arr)

[[[18 18 18]
  [18 18 18]
  [18 18 18]]]


In [ ]:
import numpy as np
arr = np.full((1,4,4),17)
print(arr)

[[[17 17 17 17]
  [17 17 17 17]
  [17 17 17 17]
  [17 17 17 17]]]


In [ ]:
import numpy as np
arr = np.full((1,5,5),10)
print(arr)

[[[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]]


In [ ]:
import numpy as np
arr = np.full((1,6,6),7)
print(arr)

[[[7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]
  [7 7 7 7 7 7]]]


In [ ]:
#4-D array

import numpy as np
arr = np.full((1,1,2,2),45)
print(arr)

[[[[45 45]
   [45 45]]]]


In [ ]:
import numpy as np
arr = np.full((2,1,3,3),18)
print(arr)

[[[[18 18 18]
   [18 18 18]
   [18 18 18]]]


 [[[18 18 18]
   [18 18 18]
   [18 18 18]]]]


In [ ]:
import numpy as np
arr = np.full((2,1,4,4),17)
print(arr)

[[[[17 17 17 17]
   [17 17 17 17]
   [17 17 17 17]
   [17 17 17 17]]]


 [[[17 17 17 17]
   [17 17 17 17]
   [17 17 17 17]
   [17 17 17 17]]]]


In [ ]:
import numpy as np
arr = np.full((2,1,5,5),10)
print(arr)

[[[[10 10 10 10 10]
   [10 10 10 10 10]
   [10 10 10 10 10]
   [10 10 10 10 10]
   [10 10 10 10 10]]]


 [[[10 10 10 10 10]
   [10 10 10 10 10]
   [10 10 10 10 10]
   [10 10 10 10 10]
   [10 10 10 10 10]]]]


In [ ]:
import numpy as np
arr = np.full((1,1,6,6),7)
print(arr)

[[[[7 7 7 7 7 7]
   [7 7 7 7 7 7]
   [7 7 7 7 7 7]
   [7 7 7 7 7 7]
   [7 7 7 7 7 7]
   [7 7 7 7 7 7]]]]


In [ ]:
#5-D array

import numpy as np
arr = np.full((1,1,1,2,2),45)
print(arr)

[[[[[45 45]
    [45 45]]]]]


In [ ]:
import numpy as np
arr = np.full((1,1,1,3,3),18)
print(arr)

[[[[[18 18 18]
    [18 18 18]
    [18 18 18]]]]]


In [ ]:
import numpy as np
arr = np.full((1,1,1,4,4),17)
print(arr)

[[[[[17 17 17 17]
    [17 17 17 17]
    [17 17 17 17]
    [17 17 17 17]]]]]


In [ ]:
import numpy as np
arr = np.full((1,1,1,5,5),10)
print(arr)

[[[[[10 10 10 10 10]
    [10 10 10 10 10]
    [10 10 10 10 10]
    [10 10 10 10 10]
    [10 10 10 10 10]]]]]


In [ ]:
import numpy as np
arr = np.full((1,1,1,6,6),7)
print(arr)

[[[[[7 7 7 7 7 7]
    [7 7 7 7 7 7]
    [7 7 7 7 7 7]
    [7 7 7 7 7 7]
    [7 7 7 7 7 7]
    [7 7 7 7 7 7]]]]]


6)identity matrix:

- np.eye(one number for same rows and columns)
- it works for only 2-D dimesion
- values are in float data type
- if we want values in int, np.eye(value,dtype=int)

In [ ]:
#2-D array

import numpy as np
arr = np.eye(3)    #number represents for rows and columns
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
arr = np.eye(4,dtype = int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
import numpy as np
arr = np.eye(5,dtype=int)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
import numpy as np
arr = np.eye(6,dtype = int)
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [ ]:
import numpy as np
arr = np.eye(10,dtype = int)
print(arr)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [ ]:
#3-D array

import numpy as np
arr = np.eye(3,5,5,dtype = int) # it takes only first two values as rows and colomns and ignore the last value
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
import numpy as np
arr = np.eye(1,1,2,4) #if we take 4 values it shows error so the identity matrix works on 2-D array only
print(arr)

7)array with random values

- if we run the code multiple times by using random method simultaneously value will change
- the values will occcurs between 0 to 1
- syntax-> np.random.random([shape,rows,col])

In [ ]:
#1-D array

import numpy as np
arr = np.random.random(4)  #(columns)
print(arr)

[0.84948035 0.51885996 0.03940428 0.05695985]


In [ ]:
#2-D array
import numpy as np
arr = np.random.random([2,2])  #(rows,colomns)
print(arr)

[[0.87538916 0.40723875]
 [0.67047647 0.21928933]]


In [ ]:
#3-d ARRAY
import numpy as np
arr = np.random.random([1,3,3])    #(shape,row,col)
print(arr)

[[[0.11779895 0.68418469 0.22453606]
  [0.90146349 0.27876519 0.70236347]
  [0.70042976 0.52385578 0.10709087]]]


In [ ]:
#4-D array
import numpy as np
arr = np.random.random([1,1,4,4])
print(arr)

[[[[0.49399102 0.40840217 0.98588157 0.97706165]
   [0.97395825 0.96790695 0.0535049  0.0367957 ]
   [0.62347258 0.61022155 0.85732645 0.92785142]
   [0.70709074 0.90623705 0.01012557 0.6491252 ]]]]


In [ ]:
#5-D array
import numpy as np
arr = np.random.random([1,1,1,5,5])
print(arr)

[[[[[0.3086232  0.2034635  0.8361983  0.19572192 0.97314219]
    [0.54991207 0.5060358  0.19257611 0.5934896  0.82285101]
    [0.99547683 0.49049167 0.77077249 0.2397668  0.42652173]
    [0.02307284 0.89778586 0.87430432 0.17673346 0.93928918]
    [0.01302493 0.85117198 0.75713032 0.44828029 0.92588501]]]]]


for a particular range in integer value
- np.random.randint(start,ending values)

In [ ]:
import numpy as np
arr = np.random.randint(1,50)  #(start,ending value)
print(arr)

24


In [ ]:
import numpy as np
arr = np.random.randint(45,78)
print(arr)

59


In [ ]:
import numpy as np
arr = np.random.randint(73,101)
print(arr)

98


In [ ]:
import numpy as np
arr = np.random.randint(6273,8122380)
print(arr)

2848635


In [ ]:
import numpy as np
arr = np.random.randint(883348,8712328)
print(arr)

1070015


9)shape of array:

- weather it is in 1-D,2-D,3-D,,any thing we use "shape" method

In [ ]:
#1-D array

import numpy as np
arr = np.array([1,2,3])
print(arr.shape)

(3,)


In [ ]:
#2-D array
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [6,7,8]])
print(arr.shape)

(3, 3)


In [ ]:
#3-D array
import numpy as np
arr = np.array([[[1,2,3],
                 [4,5,6],
                  [7,8,9]]])
print(arr.shape)

(1, 3, 3)


In [ ]:
#4-D array
import numpy as np
arr = np.array([[[[1,2,3],
                  [4,5,6],
                  [7,8,9]]]])
print(arr.shape)

(1, 1, 3, 3)


In [ ]:
#5-D array
import numpy as np
arr = np.array([[[[[1,2,3],
                   [4,5,6],
                    [7,8,9]]]]])
print(arr.shape)

(1, 1, 1, 3, 3)


10) find no of elements in array

- to find no of elements in array we can use size method

In [ ]:
#1-D array
import numpy as np
arr = np.array([1,2,3])
print(arr.size)

3


In [ ]:
#2-D array
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.size)

6


In [ ]:
#3-D array
import numpy as np
arr = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
print(arr.size)

9


In [ ]:
#4-D array
import numpy as np
arr = np.array([[[[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]]]])
print(arr.size)

12


In [ ]:
#5-D array
import numpy as np
arr = np.array([[[[[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12],
                   [13,14,15]]]]])
print(arr.size)

15


11)find length of array

- it will only identify the rows
- using "len" keyword

In [ ]:
#1-D array

import numpy as np
arr = np.array([1,2,3,2,4,3,2,23])
len(arr)

# len is not applicable for 1-D array

8

In [ ]:
#2-D array
import numpy as np
arr = np.array([[1,2,3],
                [3,4,5]])
print(len(arr))

2


In [ ]:
import numpy as np
arr = np.array([[12,24,13123],
                [32,324,3344],
                [12233,43,23],
                [12,24,24]])
print(len(arr))

4


In [ ]:
#3-D array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],
                [[2,4,1],[343,23,23]],
                [[2,4,1],[343,23,23]],
                [[4,13,42],[3,54,23]]])
print(len(arr))

4


In [ ]:
#4-D array
import numpy as np
arr = np.array([[[[1,2,3],[42,44,23],[123,233,3]]],
                [[[223,43,33],[123,44,23],[13,54,223]]],
                [[[33,3,23],[234,343,23],[233,344,34]]]])
print(len(arr))

3


In [ ]:
#5-D array
import numpy as np
arr = np.array([[[[[23,32,12],[133,343,22],[1323,3434,2223],[134,54,43]]]],
                   [[[[123,233,123],[133,53,53],[44,54,23],[24,65,34]]]],
                   [[[[1344,244,223],[244,24,6],[653,24,66],[34,5,24]]]],
                   [[[[24343,244,23],[144,45,23],[44,544,34],[455,213,334]]]]])
print(len(arr))

4


#accessing elements from array

- we can access an array element by using it index number
- the index number in numpy arrays starts with zero
- it means first element index position is zero
- by using index value we can apply arthematic operations

In [ ]:
# find value in array by using index
#1-D array

import numpy as np
arr = np.array([1,2,3,4])
print(arr[3])

4


In [ ]:
#applying arthematic operators
import numpy as np
arr = np.array([3,12,524,53,45,2244,45,5,2344])
print(arr[4]+arr[3]-arr[5]/arr[2]*arr[7]//arr[8])

98.0


In [ ]:
# find value in array by using index
#2-D array

import numpy as np
arr = np.array([[1,2,3],     #0 - index position
               [4,5,6],     #1
               [7,8,9]])    #2

print(arr[0,1])  #([1-D index,value index])

2


In [ ]:
#3-D array
import numpy as np
                   #0      #1  ->1-D index
arr = np.array([[[1,2,3],[4,5,6]],         #0  ->2-D index
                 [[7,8,9],[10,11,12]],      #1
                 [[13,14,15],[16,17,18]]]) #2
print(arr[1,0,2])    #(2D,1D,value index)

9


In [18]:
#4-D array
import numpy as np
                                  #0                                 #1                            #2         ->2-D index
                       #0        #1        #2            #0         #1       #2            #0           #1         #2      ->1-D index
arr = np.array([[[[121,311,31],[1,2,3],[213,123,32]],[[12,323,12],[4,5,6],[23,41,23]],[[1231,1223,42],[7,8,9],[23,4213,23]]],                    #0 ->3-D index
                [[[122,23,32],[112,334,545],[23,323,434]],[[133,23,43],[34,34,12],[343,134,44]],[[13,43,123],[22,44,12],[44,12,43]]],            #1
                [[[123,213,332],[12,45,54],[1344,341,1234]],[[123,22,33],[23,34,23],[124,4324,13]],[[1223,42,23],[23,54,23],[14,4134,123]]]])    #2
print(arr[1,2,2,2])    #(3D,2D,1D,value)

43


In [33]:
#5-D array
import numpy as np
#[[[[[134,213,22],[12,42,12]],[[123,23,112],[23,12,4]]],[[[23,23,12],[13,42,1]],[[123,42,232],[23,2,13]]]]]
                                              #0                                                    #1                                               #2    ->3-D index
                                #0                         #1                              #0                         #1                          #0                              #1           -> 2-D index
                          #0            #1            #0          #1               #0            #1           #0           #1              #0               #1              #0           #1   ->1_D index
arr = np.array([[[[[1231,3341,123],[123,41,13]],[[123,431,123],[123,41,13]]],[[[123,4133,33],[123,41,23]],[[123,41,123],[144,24,1]]],[[[123,413,33],[1223,423,133]],[[123,41333,13],[134,22,243]]]],      #0 ->4-D index
                [[[[1223,13321,333],[1234,123,42]],[[1233,131,1231],[1234,131,223]]],[[[342,4,23],[124,341,13]],[[123,123,214],[14,11,13]]],[[[14,14,13],[234,432,3324]],[[123,123,13],[13,4131,123]]]],  #1
                [[[[123,411,23],[123,3123,23]],[[123,41,23],[123,41,123]]],[[[123,34,1223],[123,121,123]],[[123,412,43],[123,123,11]]],[[[123,4133,123],[34,32,234]],[[123,41,123],[234,52,114]]]]])      #2
print(arr[2,2,1,1,1])    #(4D,3D,2D,1D,value)


52


#data types in numpy:

- numpy has some extra datatypes and refers the datatypes with one character
- types of data types metioned below
- 1)"i" - integer
- 2)"f" - float
- 3)np.complex128 - complex
- 4)"bool" - boolean
- 5)"M" - datetime
- 6)"O" - object
- 7)"S" - string

In [52]:
from os.path import normpath
#examples for data types
#1)integer
import numpy as np
arr = np.array([1.432,2.12,4.42,122.43,244.2,223.3],dtype = "i")
print(arr)
print(arr.dtype)

[  1   2   4 122 244 223]
int32


In [53]:
#2)float
import numpy as np
arr = np.array([21,231,21,23,12,23,1,23,133],dtype = "f")
print(arr)
print(arr.dtype)

[ 21. 231.  21.  23.  12.  23.   1.  23. 133.]
float32


In [68]:
#complex
import numpy as np
arr = np.array([12,23,12,42],dtype = np.complex128)
print(arr)
print(arr.dtype)

[12.+0.j 23.+0.j 12.+0.j 42.+0.j]
complex128


In [57]:
#boolen
import numpy as np
arr = np.array([123,123,1,232214,0,-45,344,41,414,4,134,14636],dtype = "bool")
print(arr)
print(arr.dtype)

[ True  True  True  True False  True  True  True  True  True  True  True]
bool


In [108]:
#5)datetime
import numpy as np
from datetime import datetime
arr = np.datetime64("now")
print(arr)

2024-11-14T08:40:20


In [104]:
#6)object
#convert datetime64 to datetime object
import numpy as np
from datetime import datetime
arr = np.datetime64("now")
newarr = arr.astype(datetime)
print(newarr)


2024-11-14 08:36:11


In [107]:
#convert datetime to datetime64 object
import numpy as np
from datetime import datetime
arr = datetime(2024,1,12,11,33,23)
newarr = np.datetime64(arr)
print(newarr)

2024-01-12T11:33:23.000000


In [111]:
#7)string

import numpy as np
arr = np.array([123,41,12,143,13123,133,1231],dtype = "S")
print(arr)
print((arr.dtype))

[b'123' b'41' b'12' b'143' b'13123' b'133' b'1231']
|S5


change datatype into another data type

In [112]:
#int to float
import numpy as np
arr = np.array([12,23,42,32,23,133])
newarr = arr.astype("f")
print(newarr)

[ 12.  23.  42.  32.  23. 133.]


In [113]:
#float to int
import numpy as np
arr = np.array([12.42,42.42,24.24,42.23])
print(arr.astype("i"))

[12 42 24 42]


In [116]:
#int to boolean
import numpy as np
arr = np.array([123,42,1,0,0,1,134,2,-3,-54,-33])
print(arr.astype("bool"))

[ True  True  True False False  True  True  True  True  True  True]


#methods


1)copy():

- it is simply known as backup

In [117]:
import numpy as np
arr = np.array([123,42,24,12,244,1,34,34,344,4,233,4,4])
newarr = arr.copy()
arr[5] = 2323
print(newarr)
print(arr)

[123  42  24  12 244   1  34  34 344   4 233   4   4]
[ 123   42   24   12  244 2323   34   34  344    4  233    4    4]


2)view():

- it is just for view purpose only

In [119]:
import numpy as np
arr = np.array([23,533,223,344,23,334])
newarr = arr.view()
arr[4] = 45
print(arr)
print(newarr)

[ 23 533 223 344  45 334]
[ 23 533 223 344  45 334]


#reshaping arrays:

- reshaping means change the shape of an array
- the shape of an element means no of rows and columns
- in reshaping we can add (or) remove dimensions (or) change the no of elements in each dimension
- we can simply use multiplication because it is matrix

In [124]:
#1-D arrays to 2-D arrays
import numpy as np
arr = np.array([123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2])  #16 elements
print(arr.reshape(4,4))   #(1*16,2*8,4*4,8*2,16*1)
print(arr.reshape(1,16))

[[123  43   2  43]
 [  2  33   4   2]
 [423  34  22   2]
 [ 23  14 223   2]]
[[123  43   2  43   2  33   4   2 423  34  22   2  23  14 223   2]]


In [126]:
#1-D to 3-D
import numpy as np
arr = np.array([123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2])  #16 elements
print(arr.reshape(1,4,4))

[[[123  43   2  43]
  [  2  33   4   2]
  [423  34  22   2]
  [ 23  14 223   2]]]


In [127]:
#1-D to 4-D
import numpy as np
arr =np.array([123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2])  #16 elements
print(arr.reshape(1,1,4,4))

[[[[123  43   2  43]
   [  2  33   4   2]
   [423  34  22   2]
   [ 23  14 223   2]]]]


In [128]:
#1-D to 5-D
import numpy as np
arr = np.array([123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2])  #16 elements
print(arr.reshape(1,1,1,4,4))

[[[[[123  43   2  43]
    [  2  33   4   2]
    [423  34  22   2]
    [ 23  14 223   2]]]]]


In [129]:
#2-D to 1-D
import numpy as np
arr = np.array([[123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2]])  #16 elements
print(arr.reshape(16))

[123  43   2  43   2  33   4   2 423  34  22   2  23  14 223   2]


In [130]:
#2-D to 3-D
import numpy as np
arr = np.array([[123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2]])  #16 elements
print(arr.reshape(1,4,4))

[[[123  43   2  43]
  [  2  33   4   2]
  [423  34  22   2]
  [ 23  14 223   2]]]


In [132]:
#2-D to 4-D
import numpy as np
arr = np.array([[123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2]])  #16 elements
print(arr.reshape(2,2,2,2))

[[[[123  43]
   [  2  43]]

  [[  2  33]
   [  4   2]]]


 [[[423  34]
   [ 22   2]]

  [[ 23  14]
   [223   2]]]]


In [133]:
#2-D to 5-D
import numpy as np
arr = np.array([[123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2]])  #16 elements
print(arr.reshape(1,2,2,2,2))

[[[[[123  43]
    [  2  43]]

   [[  2  33]
    [  4   2]]]


  [[[423  34]
    [ 22   2]]

   [[ 23  14]
    [223   2]]]]]


In [134]:
#3-D to 1-D
import numpy as np
arr = np.array([[[123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2]]])  #16 elements
print(arr.reshape(16))

[123  43   2  43   2  33   4   2 423  34  22   2  23  14 223   2]


In [135]:
#3-D to 2-D
import numpy as np
arr = np.array([[[123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2]]])  #16 elements
print(arr.reshape(4,4))

[[123  43   2  43]
 [  2  33   4   2]
 [423  34  22   2]
 [ 23  14 223   2]]


In [138]:
#3-D to 4-D
import numpy as npp
arr =  np.array([[[123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2]]])  #16 elements
print(arr.reshape(1,2,4,2))

[[[[123  43]
   [  2  43]
   [  2  33]
   [  4   2]]

  [[423  34]
   [ 22   2]
   [ 23  14]
   [223   2]]]]


In [139]:
#3-D to 5-D
import numpy as np
arr = np.array([[[123,43,2,43,2,33,4,2,423,34,22,2,23,14,223,2]]])  #16 elements
print(arr.reshape(1,2,2,2,2))

[[[[[123  43]
    [  2  43]]

   [[  2  33]
    [  4   2]]]


  [[[423  34]
    [ 22   2]]

   [[ 23  14]
    [223   2]]]]]


In [142]:
#4-D to 1-D
import numpy as np
arr = np.array([[[[[123,43],[2,43]],[[33,4],[2,423]],[[34,22],[2,23]],[[14,223],[2,65]]]]])  #16 elements
print(arr.reshape(16))

[123  43   2  43  33   4   2 423  34  22   2  23  14 223   2  65]


In [143]:
#4-D to 2-D
import numpy as np
arr = np.array([[[[[123,43],[2,43]],[[33,4],[2,423]],[[34,22],[2,23]],[[14,223],[2,65]]]]])
print(arr.reshape(4,4))

[[123  43   2  43]
 [ 33   4   2 423]
 [ 34  22   2  23]
 [ 14 223   2  65]]


In [144]:
#4-D to 3-D
import numpy as np
arr = np.array([[[[[123,43],[2,43]],[[33,4],[2,423]],[[34,22],[2,23]],[[14,223],[2,65]]]]])
print(arr.reshape(2,4,2))

[[[123  43]
  [  2  43]
  [ 33   4]
  [  2 423]]

 [[ 34  22]
  [  2  23]
  [ 14 223]
  [  2  65]]]


In [145]:
#4-D to 5-D
import numpy as np
arr = np.array([[[[[123,43],[2,43]],[[33,4],[2,423]],[[34,22],[2,23]],[[14,223],[2,65]]]]])
print(arr.reshape(1,2,2,2,2))

[[[[[123  43]
    [  2  43]]

   [[ 33   4]
    [  2 423]]]


  [[[ 34  22]
    [  2  23]]

   [[ 14 223]
    [  2  65]]]]]


In [156]:
#5-D to 1-D
import numpy as np
arr = np.array([[[[[123,411,23],[123,3123,23]]],[[[123,34,1223],[123,121,123]]],[[[123,4133,123],[34,32,234]]]]])  #18 elements
print(arr.reshape(18))

[ 123  411   23  123 3123   23  123   34 1223  123  121  123  123 4133
  123   34   32  234]


In [158]:
#5-D to 2-D
import numpy as np
arr= np.array([[[[[123,411,23],[123,3123,23]]],[[[123,34,1223],[123,121,123]]],[[[123,4133,123],[34,32,234]]]]])  #18 elements
print(arr.reshape(2,9))

[[ 123  411   23  123 3123   23  123   34 1223]
 [ 123  121  123  123 4133  123   34   32  234]]


In [159]:
#5-D to 3-D
import numpy as np
arr = np.array([[[[[123,411,23],[123,3123,23]]],[[[123,34,1223],[123,121,123]]],[[[123,4133,123],[34,32,234]]]]])  #18 elements
print(arr.reshape(2,3,3))

[[[ 123  411   23]
  [ 123 3123   23]
  [ 123   34 1223]]

 [[ 123  121  123]
  [ 123 4133  123]
  [  34   32  234]]]


In [161]:
#5-D to 4-D
import numpy as np
arr =np.array([[[[[123,411,23],[123,3123,23]]],[[[123,34,1223],[123,121,123]]],[[[123,4133,123],[34,32,234]]]]])  #18 elements
print(arr.reshape(1,3,3,2))

[[[[ 123  411]
   [  23  123]
   [3123   23]]

  [[ 123   34]
   [1223  123]
   [ 121  123]]

  [[ 123 4133]
   [ 123   34]
   [  32  234]]]]


#mathematical operations using arrays in numpy

In [162]:
#adition
import numpy as np
x = np.array([12,32,1,3,3])
y = np.array([234,54,3,5,3])
print(np.add(x,y))

[246  86   4   8   6]


In [163]:
#subtraction
import numpy as np
x = np.array([12,32,1,3,3])
y = np.array([234,54,3,5,3])
print(np.subtract(x,y))

[-222  -22   -2   -2    0]


In [165]:
#multiplication
import numpy as np
x = np.array([12,32,1,3,3])
y = np.array([234,54,3,5,3])
print(np.multiply(x,y))

[2808 1728    3   15    9]


In [167]:
#division
import numpy as np
x = np.array([12,32,1,3,3])
y = np.array([234,54,3,5,3])
print(np.divide(x,y))

[0.05128205 0.59259259 0.33333333 0.6        1.        ]


In [173]:
#squareroot
import numpy as np
x = np.array([12,32,1,3,3])
y = np.array([234,54,3,5,3])
print(np.sqrt(x))
print(np.sqrt(y))

[3.46410162 5.65685425 1.         1.73205081 1.73205081]
[15.29705854  7.34846923  1.73205081  2.23606798  1.73205081]


In [174]:
#square (power)
import numpy as np
x = np.array([12,32,1,3,3])
y = np.array([234,54,3,5,3])
print(np.square(x))
print(np.square(y))

[ 144 1024    1    9    9]
[54756  2916     9    25     9]


#sorting arrays:

- sorting the arrays means like ascending order it can arrange the order in sequence
- the numpy object has function called sort()

In [177]:
import numpy as np
arr = np.array([123,43,43,23,434,33,23,224,32,23,1,3,2,32,3,23])
print(np.sort(arr))

[  1   2   3   3  23  23  23  23  32  32  33  43  43 123 224 434]


#slicing arrays:

- slicing in python means taking elements from one given index to another index
- we can mention slicing by [start:stop] or [start:stop:step] index position
- if we dont pass anything on starting it considered as "0"
- if wee dont pass anything on end it can takes upto last value
- if we dont pass step it considered as "1" ,it is like n-1

In [178]:
#slicing in 1-D
import numpy as np
arr = np.array([12,344,13,34,23,2,24,4,5,3,4,4])
print(arr[0:6])
print(arr[4:])
print(arr[:5])
print(arr[:])
print(arr[::3])


[ 12 344  13  34  23   2]
[23  2 24  4  5  3  4  4]
[ 12 344  13  34  23]
[ 12 344  13  34  23   2  24   4   5   3   4   4]
[12 34 24  3]


In [186]:
#slicing in 2-D
import numpy as np
                      #0                  #1               #2           ->1-D index
arr = np.array([[12,344,13,34,23,2],[24,4,5,3,4,4],[123,5344,24,23,44,3]])  #0  2-D index
print(arr[0:3,1:5])  #(1-D index,values)

[[ 344   13   34   23]
 [   4    5    3    4]
 [5344   24   23   44]]


In [209]:
#slicing in 3-D
import numpy as np
                       #0                #1         ->1-D index
arr = np.array([[[211,45,26,44,83],[18,92,734,73,63]],       #0   ->2-D index
                [[211,4,2,43,23],[13,42,134,23,53]],         #1
                [[123,4334,23,222,23],[13,423,13,42,13]]])   #2
print(arr[0:3,0:2,1:4])   #(2-D,1-D slicing,values)

[[[  45   26   44]
  [  92  734   73]]

 [[   4    2   43]
  [  42  134   23]]

 [[4334   23  222]
  [ 423   13   42]]]


In [212]:
#slicing in 4-D
import numpy as np
                            #0                        #1          ->2-D index
                      #0           #1            #0         #1    ->1-D index
arr = np.array([[[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]],             #0  ->3-D index
                [[[21,22,23,24,25],[26,27,28,29,30]],[[31,32,33,34,35],[36,37,38,39,40]]],    #1
                [[[41,42,43,44,45],[46,47,48,49,50]],[[51,52,53,54,55],[56,57,58,59,60]]]])   #2
print(arr[0:3,0:2,0:2,2:5])   #(3-D,2-D,1-D,values)

[[[[ 3  4  5]
   [ 8  9 10]]

  [[13 14 15]
   [18 19 20]]]


 [[[23 24 25]
   [28 29 30]]

  [[33 34 35]
   [38 39 40]]]


 [[[43 44 45]
   [48 49 50]]

  [[53 54 55]
   [58 59 60]]]]


In [223]:
#slicing in 5-D
import numpy as np
                                              #0                                                    #1                                               #2    ->3-D index
                                #0                         #1                              #0                         #1                          #0                              #1           -> 2-D index
                          #0            #1            #0          #1               #0            #1           #0           #1              #0               #1              #0           #1   ->1_D index
arr = np.array([[[[[1231,3341,123],[123,41,13]],[[123,431,123],[123,41,13]]],[[[123,4133,33],[123,41,23]],[[123,41,123],[144,24,1]]],[[[123,413,33],[1223,423,133]],[[123,41333,13],[134,22,243]]]],      #0 ->4-D index
                [[[[1223,13321,333],[1234,123,42]],[[1233,131,1231],[1234,131,223]]],[[[342,4,23],[124,341,13]],[[123,123,214],[14,11,13]]],[[[14,14,13],[234,432,3324]],[[123,123,13],[13,4131,123]]]],  #1
                [[[[123,411,23],[123,3123,23]],[[123,41,23],[123,41,123]]],[[[123,34,1223],[123,121,123]],[[123,412,43],[123,123,11]]],[[[123,4133,123],[34,32,234]],[[123,41,123],[234,52,114]]]]])      #2
print(arr[0:3,1:2,0:2,0:2,1:4])    #(4D,3D,2D,1D,value)


[[[[[4133   33]
    [  41   23]]

   [[  41  123]
    [  24    1]]]]



 [[[[   4   23]
    [ 341   13]]

   [[ 123  214]
    [  11   13]]]]



 [[[[  34 1223]
    [ 121  123]]

   [[ 412   43]
    [ 123   11]]]]]
